/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.telas;

/**
 *
 * @author Weslley Silva
 */
import java.sql.*;
import br.com.biblioteca.dal.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class TelaEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    
         Connection conexao = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        public TelaEmprestimo() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
      
         private void pesquisar() {
        String sql = "select * from livro where titulo like ?";
        try {
            pst = conexao.prepareStatement(sql);
            
            //passando o conteudo da caixa de conteudo para ?
            // atenção com % que é contiuação  da String sql
            pst.setString(1, txtPesquisa.getText() + "%");
            rs = pst.executeQuery();
            // alinha abaixo usar a biblioteca rs2xml que foi importada parapreencher a tabela
            tblEmprestimo.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }
         public void setar_campo() {
        
        int setar = tblEmprestimo.getSelectedRow();
       
        lblTitulo.setText(tblEmprestimo.getModel().getValueAt(setar, 1).toString());
        lblAno.setText(tblEmprestimo.getModel().getValueAt(setar, 3).toString());
        lblVolume.setText(tblEmprestimo.getModel().getValueAt(setar, 4).toString());
        lblEdicao.setText(tblEmprestimo.getModel().getValueAt(setar, 5).toString());
        lblEstante.setText(tblEmprestimo.getModel().getValueAt(setar, 6).toString());
        lblValor.setText(tblEmprestimo.getModel().getValueAt(setar, 7).toString());
        lblEditora.setText(tblEmprestimo.getModel().getValueAt(setar, 8).toString());
         lblAutor.setText(tblEmprestimo.getModel().getValueAt(setar, 9).toString());
        
     
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblEstante = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        lblEdicao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Emprestimo");

        tblEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmprestimo);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/icones/1478118009_Zoom.png"))); // NOI18N

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        lblTitulo.setText("....");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(50, 30, 150, 30);

        lblAno.setText("....");
        jPanel1.add(lblAno);
        lblAno.setBounds(120, 60, 50, 30);

        lblEditora.setText("....");
        jPanel1.add(lblEditora);
        lblEditora.setBounds(60, 100, 130, 30);

        lblAutor.setText("....");
        jPanel1.add(lblAutor);
        lblAutor.setBounds(100, 140, 130, 30);

        lblEstante.setText("....");
        jPanel1.add(lblEstante);
        lblEstante.setBounds(310, 20, 140, 40);

        lblValor.setText("....");
        jPanel1.add(lblValor);
        lblValor.setBounds(310, 50, 110, 30);

        lblVolume.setText("....");
        jPanel1.add(lblVolume);
        lblVolume.setBounds(320, 90, 140, 30);

        lblEdicao.setText("....");
        jPanel1.add(lblEdicao);
        lblEdicao.setBounds(310, 130, 120, 30);

        jLabel2.setText("Título: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 40, 30);

        jLabel3.setText("Ano de Publicação");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 64, 110, 30);

        jLabel4.setText("Editora:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 100, 50, 30);

        jLabel5.setText("Autor/Autores: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 90, 30);

        jLabel6.setText("Estante: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 24, 70, 30);

        jLabel7.setText("Valor:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 50, 60, 30);

        jLabel8.setText("Volume: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 90, 50, 30);

        jLabel9.setText("Edição: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 130, 50, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/icones/1477932390_personal-information.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 30, 172, 160);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Informações:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 10, 100, 20);

        lblSituacao.setForeground(new java.awt.Color(204, 0, 0));
        lblSituacao.setText("....");
        jPanel1.add(lblSituacao);
        lblSituacao.setBounds(480, 10, 40, 30);

        jLabel12.setText("Situação:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(405, 10, 60, 30);

        jButton1.setText("Efetuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void tblEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmprestimoMouseClicked
        // TODO add your handling code here:
        setar_campo();
    }//GEN-LAST:event_tblEmprestimoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEdicao;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblEstante;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JTable tblEmprestimo;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
